name: Deploy saleinfo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Chromedriver
        run: |
          # 下载和安装Chromedriver 117版本
          CHROMEDRIVER_VERSION="117.0.5938.88"
          wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/117.0.5938.92/linux64/chrome-linux64.zip
          unzip chromedriver_linux64.zip
          chmod +x chromedriver
          mv chromedriver /usr/local/bin/

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install pandas
        run: pip install pandas


      - name: Deploy to AWS
        env:  # 设置环境变量
          AWS_RDS_HOST: ${{ secrets.AWS_RDS_HOST }}
          AWS_RDS_PORT: ${{ secrets.AWS_RDS_PORT }}
          AWS_RDS_USER: ${{ secrets.AWS_RDS_USER }}
          AWS_RDS_PASSWORD: ${{ secrets.AWS_RDS_PASSWORD }}
        run: |
          # 在这里执行部署操作，包括启动你的Python应用程序
          python main.py

